#!/bin/bash

SB_CONFIG="$HOME/.simple-backup.conf"
if [ ! -f "$SB_CONFIG" ]; then
    echo "Error: Cannot find $SB_CONFIG"
    exit 1
fi
. "$SB_CONFIG"

if [ -z "$SB_SRC" ]; then
    echo "Error: SB_SRC not defined config."
    exit 1
fi
if [ ! -d "$SB_SRC" ]; then
    echo "Error: Source $SB_SRC is not a directory."
    exit 1
fi

if [ -z "$SB_DST" ]; then
    echo "Error: SB_DST not defined config."
    exit 1
fi
if [ ! -e "$SB_DST" ]; then
    [ "x$1" != "xtrigger" ] && echo "Error: Destination $SB_DST doesn't exist. Run '$0 init' to create it."
    exit 1
fi
if [ ! -d "$SB_DST" ]; then
    [ "x$1" != "xtrigger" ] && echo "Error: Destination $SB_DST is not a directory."
    exit 1
fi

SB_MARKER="$SB_DST/0THIS_IS_A_BACKUP"
SB_LOCK="$SB_DST/simple-backup.lock"
SB_LOG="$HOME/simple-backup.log"

if [ ! -e "$SB_MARKER" ]; then
    echo "Error: Destination not marked as backup folder. Run '$0 init' to initialise it."
    exit 1
fi

if [ -e "$SB_LOCK" ] && ; then
    if ps -p `cat "$SB_LOCK"` >&/dev/null; then
        echo "Warning: Stale lock file found, running anyway."
    else
        [ "x$1" != "xtrigger" ] && echo "Error: Previous instance is still running."
        exit 1
    fi
fi

backup() {
    rsync -av --delete "$SB_SRC/." "$SB_DST"
}

echo $$ >"$SB_LOCK"

case "$1" in
    run|)
        backup || {
            echo "Error: Backup had errors."
        }
        touch "$SB_MARKER"
        ;;
    trigger)
        if [ ! -z "$SB_MAXAGE" ]; then
            SECONDS_PER_DAY=$((24*3600))
            AGE=$(( ( `date +%s` - `stat -c%Y "$SB_MARKER"`) / $SECONDS_PER_DAY ))
            if [ $AGE -ge $SB_MAXAGE ]; then
                if [ -z $DISPLAY ]; then
                    DISPLAY=`find-displays | head -1`
                fi
                if zenity --question --text="Last backup was $AGE days ago. Run backup now?"; then
                    backup >&"$SB_LOG" && {
                        rm -f "$SB_LOG"
                        zenity --info --text="Backup was successful."
                    } || {
                        zenity --error --text="Backup has errors. See $SB_LOG for details."
                    }
                fi
                touch "$SB_MARKER"
            fi
        else
            echo "Error: SB_MAXAGE not specified in config."
        fi
        ;;
    init)
        mkdir -p "$SB_DST"
        touch "$SB_MARKER"
        ;;
    *)
        echo "Error: Unknown command $1"
        echo "Usage: $0 <init|run|trigger>"
        ;;
esac

rm -f "$SB_LOCK"
